### ISSUE TITLE
Code for repurposing FEVER and SCIFACT

### ISSUE THREAD

**Issue by MichaelCaohn** [khuangaf/ZeroFEC#1]
Hi, 

Thanks for the greate work! I have noticed that in Section 4.1 you have mentioned that you have repurpose the FEVER and SCIFACT for the factual error correction task using two setps. 
<img width="500" alt="image" src="https://github.com/khuangaf/ZeroFEC/assets/22003919/e9c00276-751e-4680-b233-bcdfcd3f9da8">

May I know if you could also provided the code for this conversion?

Thank you very much!

**Comment by khuangaf** [comment]
Hi @MichaelCaohn, thank you for your interest in our work! 

We are still working on cleaning up our data preprocessing code. In the meantime, I can provide the Jupyter notebook we used in step 1 to form faithful claims: ([link](https://drive.google.com/file/d/1sT9yohWTzXt63Nl3nygNCLeJww-ZKzNe/view?usp=sharing)).

For step 2, please refer to [this repo](https://github.com/allenai/scientific-claim-generation).

Please let me know if there are further questions.
